Feat/edit aggrement page
VictorPozdeev1/CaseLab-ECM pull request #33
Opened 2023-12-10 09:27 UTC by AlexanderMorgunov

## Описание изменений

Создал прототип странички Aggrement Page.
Изменения на бек пока не уходят.
Сейчас нужно понять все ли устраивает концептуально, если да буду дорабатывать

## Тип изменений

- [ ] Исправление ошибки
- [ X ] Новая функциональность
- [ ] Изменение существующей функциональности
- [ ] Прочее (уточните)

## Связанные задачи/вопросы

## Yougile:
- [##CLFP-36]https://ru.yougile.com/team/28e9c2bed7c5/#CLFP-36

## Скриншоты
![image](https://github.com/VictorPozdeev1/CaseLab-ECM/assets/85402491/d1e9e32a-66d9-49a7-b28b-2513b32c25ad)

## Дополнительная информация

2023-12-10 12:00 UTC, VictorPozdeev1 reviewed
Думаю, можно продолжать в этом направлении.

P.S. Надеюсь, к тому времени, как это будет готово, мы уже будем стараться придерживаться FSD, так что структуру компонентов тоже надо будет подбить.

2023-12-10 12:00 UTC, VictorPozdeev1 commented on src/api/generated/models/DocAttributeDtoWithSelected.ts
Я тут глубоко не разбирался, но: в этой папке должны лежать автоматически сгенерированные Dto (Data Transfer Object), которые нужны для запросов к апи. Руками сюда постараемся ничего не писать. (Тем более, как я понимаю, это не Dto)

2023-12-10 12:00 UTC, VictorPozdeev1 commented on src/app/AppRoutes.tsx
> +              <AgreementsTypesPage />
Возможно, DocumentTypesPage? (и path соответствующий)

2023-12-17 18:49 UTC, VictorPozdeev1 requested changes

2023-12-17 18:49 UTC, VictorPozdeev1 commented on src/shared/api/models/DocAttributeDtoWithSelected.ts
Про этот файл я ещё в первый раз писал тебе коммент.

2023-12-17 18:49 UTC, VictorPozdeev1 commented on src/widgets/OwnDocumentsTable/OwnDocumentsTable.tsx
> +        // creationDate: new Date(d.date),
Убери, плз

2023-12-17 18:49 UTC, VictorPozdeev1 commented on src/widgets/CreateDocumentWidget/components/CreateDocumentDialogForm/CreateDocumentDialogForm.tsx
> +        ?.attributes?.map((a: DocAttributeDto) => ({
Можно убрать же?

2023-12-21 20:10 UTC, AlexanderMorgunov commented on src/api/generated/models/DocAttributeDtoWithSelected.ts
Удалил этот файл, не потребовался

2023-12-21 20:10 UTC, AlexanderMorgunov commented on src/app/AppRoutes.tsx
> +              <AgreementsTypesPage />
Исправил название на DocumentTypesPage

2023-12-21 20:11 UTC, AlexanderMorgunov commented on src/pages/AgreementsTypesPage/AgreementsTypesPage.tsx
Исправил

2023-12-21 20:11 UTC, AlexanderMorgunov commented on .vscode/settings.json
Это похоже material ui добавил

2023-12-21 20:12 UTC, AlexanderMorgunov commented on src/pages/AgreementsTypesPage/AgreementsTypesPage.tsx
> +export type agreementType = 'EVERYONE' | 'ANYONE' | 'QORUUM';
Да, насколько понимаю

2023-12-21 20:12 UTC, AlexanderMorgunov commented on src/pages/AgreementsTypesPage/AgreementsTypesPage.tsx
> +    void attributesStore.getAttributes();
Исправил названия этих методов

2023-12-21 20:12 UTC, AlexanderMorgunov commented on src/shared/api/models/DocAttributeDtoWithSelected.ts
Удалил его

2023-12-21 20:13 UTC, AlexanderMorgunov commented on src/widgets/OwnDocumentsTable/OwnDocumentsTable.tsx
> +        // creationDate: new Date(d.date),
Убрал

2023-12-21 20:13 UTC, AlexanderMorgunov commented on src/widgets/CreateDocumentWidget/components/CreateDocumentDialogForm/CreateDocumentDialogForm.tsx
> +        ?.attributes?.map((a: DocAttributeDto) => ({
Убрал

2023-12-22 10:40 UTC, VictorPozdeev1 approved these changes

2023-12-22 10:40 UTC, merged