Добавил sidebar и form на странице admin
VictorPozdeev1/CaseLab-ECM pull request #58
Opened 2024-01-19 01:46 UTC by webDevArtur

## Описание изменений

Вёрстка сайдбара и формы для админа компаний

## Тип изменений

- [ - ] Исправление ошибки
- [ - ] Новая функциональность
- [ - ] Изменение существующей функциональности
- [ - ] Прочее (уточните)

## Yougile:
https://ru.yougile.com/team/28e9c2bed7c5/#CLFP-48

## Скриншоты

-

## Дополнительная информация

2024-01-19 12:18 UTC, VictorPozdeev1 commented on src/widgets/CompanyMainControlPanel/ui/OrganizationForm.tsx
> +        <TextField
Тут выпадающий список должен быть, чтоб не вводить вручную. Возможно, с функцией поиска. Но т. к. проект учебный, пойдёт и просто селект (муишный, разумеется).

2024-01-19 12:19 UTC, VictorPozdeev1 commented on src/widgets/CompanyMainControlPanel/ui/OrganizationForm.tsx
> +          Сохранить
Мы вроде обсуждали вариант без кнопок. Решил сделать с кнопками?

2024-01-19 12:23 UTC, VictorPozdeev1 commented on src/widgets/CompanyMainControlPanel/ui/OrganizationSidebar.tsx
> +  const organizations = ['Организация 1', 'Организация 2', 'Организация 3'];
Импортни уж сразу companyStore, это ж быстро? 
Там хоть id будет для  key..

2024-01-19 12:29 UTC, VictorPozdeev1 commented on src/widgets/CompanyMainControlPanel/ui/OrganizationSidebar.tsx
> +        <Button variant="contained" color="primary">
Может, кнопку тоже по левому краю выровнять, а то выбивается как-то? Или растянуть.

2024-01-19 12:43 UTC, Slumrag commented
Непонятно зачнем вообще нужен сайдбар здесь? Представь у нас 50 организаций, мы их все в сайдбаре скроилть будем? 

Думаю стоит лейаут страницы сделать как у страницы пользователей или документов с таблицей на `DataGridView`. А форма создания организации будет открываться в модалке по нажатию кнопки "создать организацию"

2024-01-19 12:47 UTC, Slumrag commented on src/widgets/CompanyMainControlPanel/ui/OrganizationForm.tsx
> +        <Button variant="contained" color="secondary">
Кнопку отмены стоит сделать `outlined` цвета `primary` и расположить её левее кнопки "сохранить"

2024-01-19 13:19 UTC, VictorPozdeev1 commented
Ребята (Артур и тогда ещё была Зоя) на прошлой неделе рассматривали вариант сделать через таблицу - и выбрали тогда сделать с сайдбаром.
Сейчас уже поздновато начинать заново, надо просто сделать. 
В целом, я думаю, рабочие оба варианта.
И там, и там есть небольшие минусы, но ничего критичного.

2024-01-19 14:13 UTC, VictorPozdeev1 commented on src/widgets/CompanyMainControlPanel/ui/OrganizationForm.tsx
> +        <Button variant="contained" color="secondary">
> Кнопку отмены стоит сделать `outlined` цвета `primary` и расположить её левее кнопки "сохранить"

Я, если честно, тут вообще бы предпочёл вариант без кнопок.. Ну Артур решил сделать с кнопками - хорошо, его право)

2024-01-19 16:35 UTC, Slumrag commented on src/widgets/CompanyMainControlPanel/ui/OrganizationForm.tsx
> +          label="Введите название компании"
Это нужно в плейсхолдер написать

2024-01-20 11:22 UTC, VictorPozdeev1 requested changes

2024-01-20 11:22 UTC, VictorPozdeev1 commented on src/entities/company/model/CompaniesStore.ts
selectedCompanyId - это должен быть локальный стейт в том компоненте, в котором юзер выбирает компанию. А этот стор - это глобальный стор, который может параллельно использоваться РАЗНЫМИ компонентами, в каждом из которых selectedCompanyId может быть свой

2024-01-20 11:22 UTC, VictorPozdeev1 commented on src/widgets/CompanyMainControlPanel/ui/BaseCompanyMainControlPanel.tsx
> +  children?: React.ReactNode;
Не, тут не надо сайдбар сюда передавать. Сайдбар должны добавлять (или не добавлять, если он не нужен) более верхнеуровневые компоненты. Этот компонент - просто отображает одну компанию.

2024-01-20 11:22 UTC, VictorPozdeev1 commented on src/widgets/CompanyMainControlPanel/ui/CompanyForm.tsx
> +  }, [companiesStore.selectedCompanyId]);
Локальный стейт selectedCompanyId нужен

2024-01-20 11:22 UTC, VictorPozdeev1 commented on src/widgets/CompanyMainControlPanel/ui/CompanyForm.tsx
> +          disabled={companiesStore.getSelectedCompany() == null}
Выбрал вариант с одной кнопкой "Сохранить"? Тогда, по идее, у неё disabled должен вычисляться из того, были ли какие-то данные изменены. Флаг, что-то вроде changed: boolean (стейт формы). Для простоты можно его менять только в одном направлении: c false на true. А обратно в false ставить в useEffect, когда selectedCompanyId меняется.

2024-01-20 11:22 UTC, VictorPozdeev1 commented on src/widgets/CompanyMainControlPanel/ui/CompanySidebar.tsx
> +        await companiesStore._loadCompanies();
Методы с подчёркиванием рассматриваются как защищённые, не стоит их вызывать отовсюду

2024-01-20 11:22 UTC, VictorPozdeev1 commented on src/widgets/CompanyMainControlPanel/ui/CompanySidebar.tsx
> +        await companiesStore._loadCompanies();
companiesStore сам себя фетчит, если что

2024-01-20 11:22 UTC, VictorPozdeev1 commented on src/widgets/CompanyMainControlPanel/ui/CompanyForm.tsx
> +  }, [companiesStore.selectedCompanyId]);
А точнее, проп. Потому что выбирается компания не в этом компоненте.

2024-01-20 11:22 UTC, VictorPozdeev1 commented on src/widgets/CompanyMainControlPanel/ui/CompanySidebar.tsx
> +
В этот компонент надо передавать пропы selectedCompany, setSelectedCompany. А не из companiesStore их брать

2024-01-20 11:22 UTC, VictorPozdeev1 commented on src/widgets/CompanyMainControlPanel/ui/SpecificCompanyMainControlPanel.tsx
> +      <BaseCompanyMainControlPanel title={title}>
Здесь не один внутри другого, а просто рядом сайдбар и главную панель.
И вот как раз в этом компоненте как раз и должен быть стейт selectedCompany

2024-01-20 11:38 UTC, VictorPozdeev1 commented on src/widgets/CompanyMainControlPanel/ui/SpecificCompanyMainControlPanel.tsx
> +      <BaseCompanyMainControlPanel title={title}>
Апдейт!
У нас же companyId в адресной строке будет! Получается, тут даже стейт не нужен, т.к. адресная строка в роли стейта.
const {companyId} = useParams()   // import { useParams } from 'react-router-dom';

2024-01-20 11:40 UTC, VictorPozdeev1 commented on src/widgets/CompanyMainControlPanel/ui/SpecificCompanyMainControlPanel.tsx
> +      <BaseCompanyMainControlPanel title={title}>
ну и вместо setSelectedCompany, соответственно, редирект на соответствующий url через useNavigate()

2024-01-21 18:06 UTC, VictorPozdeev1 requested changes

2024-01-21 18:06 UTC, VictorPozdeev1 commented on src/widgets/CompanyMainControlPanel/ui/CompanyForm.tsx
> +import { Service as api } from '@api';
Не надо обращаться к апи из компонентов, вообще убери этот импорт.

2024-01-21 18:06 UTC, VictorPozdeev1 commented on src/widgets/CompanyMainControlPanel/ui/CompanyForm.tsx
> +      .updateOrg(Number(companyId), {
Делать через MobX

2024-01-21 18:06 UTC, VictorPozdeev1 commented on src/widgets/CompanyMainControlPanel/ui/CompanyForm.tsx
> +      .deleteOrg(Number(companyId))
Делать через MobX

2024-01-23 22:07 UTC, VictorPozdeev1 approved these changes

2024-01-23 22:09 UTC, VictorPozdeev1 commented
Принимаю, т.к. скоро уже защита, но написал в // todo несколько вещей, которые нужно бы ещё поправить

2024-01-23 22:09 UTC, merged